version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: cscbackenddocumentatie-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - swagger-ui
    restart: unless-stopped
    networks:
      - api-network

  certbot:
    image: certbot/certbot
    container_name: cscbackenddocumentatie-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;"
    restart: unless-stopped
    networks:
      - api-network

  swagger-ui:
    image: swaggerapi/swagger-ui:v4.15.5
    container_name: swagger-ui
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/csc-self-servics/api-docs/swagger.yaml # <-- IMPORTANT: New internal path for SWAGGER_JSON
      # Remove the 'URL' environment variable
    volumes:
      - ./swagger/swagger.yaml:/csc-self-servics/api-docs/swagger.yaml # <-- IMPORTANT: Mount to the new internal path
    networks:
      - api-network

networks:
  api-network:
    driver: bridge