# docker-compose.yaml
version: '3.8' # Use a recent version for better features

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/api/swagger.yaml
    volumes:
      - ./swagger/swagger.yaml:/api/swagger.yaml
    networks:
      - api-network
    # No "ports" mapping here, as Nginx will handle the external exposure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt # For SSL certificates
      - ./certbot/www:/var/www/certbot # For Let's Encrypt challenges
    depends_on:
      - swagger-ui
    networks:
      - api-network
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email timon@timonheidenreich.eu -d timonheidenreich.nl --agree-tos
    # Remove --force-renewal after initial setup to avoid hitting rate limits
    # Replace your-email@example.com with your actual email
    # This service is for initial certificate generation and renewal.
    # It will exit after running. You can set up a cron job for periodic renewal.

networks:
  api-network:
    driver: bridge