services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/.well-known:/var/www/certbot/.well-known:ro
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - swagger-ui
    restart: always

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      SWAGGER_JSON: /swagger/swagger.json
    volumes:
      - ./swagger:/swagger
    expose:
      - "8080"
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www/.well-known:/var/www/certbot/.well-known
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done;'"
    restart: unless-stopped
