openapi: 3.0.0
info:
  title: CSC Self-Service Backend API Documentatie
  description: |
    # CSC Self-Service Backend API

    Deze API documentatie beschrijft de endpoints en functionaliteiten van de CSC Self-Service Backend.
    Het systeem biedt functionaliteiten voor gebruikersbeheer en virtuele machine management.

    ## Authenticatie
    De API gebruikt JWT (JSON Web Tokens) voor authenticatie. Tokens moeten worden meegestuurd in de
    Authorization header met het format: `Bearer <token>`. Alle routes die beginnen met `/api/` vereisen deze authenticatie.

    ## Foutafhandeling
    De API gebruikt standaard HTTP statuscodes en retourneert foutmeldingen in JSON-formaat.

    ## Contact
    Voor ondersteuning of vragen:
    - Email: [timon@timonheidenreich.eu](mailto:timon@timonheidenreich.eu)
    - Discord: [Stuur een Bericht](https://discord.com/users/760123997475700756)
    - iMessage/SMS: `timon@timonheidenreich.eu` (alleen voor iOS gebruikers)

  version: 1.0.0
  contact:
    name: CSC Support Team

servers:
  - url: https://api.dev.ikwileenserver.open-ict.hu
    description: dev server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Foutmelding
    UserInfo:
      type: object
      properties:
        email:
          type: string
        student_id:
          type: integer
        home_ip:
          type: string
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    CreateServerRequest:
      type: object
      properties:
        name:
          type: string
        memory:
          type: integer
        cores:
          type: integer
        DiskSize:
          type: integer
        description:
          type: string
        os:
          type: string
        subdomain:
          type: string

paths:
  /auth/login:
    post:
      summary: Inloggen
      description: Authenticeer een gebruiker en genereer een JWT token
      tags:
        - Authenticatie
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Succesvol ingelogd
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token
        "401":
          description: Ongeldige inloggegevens

  /auth/resetRequest:
    post:
      summary: Wachtwoordreset aanvragen
      description: Vraag een wachtwoordreset aan
      tags:
        - Authenticatie
      responses:
        "200":
          description: Reset aanvraag succesvol verzonden

  /auth/resetPassword:
    post:
      summary: Wachtwoord resetten
      description: Voer een wachtwoordreset uit
      tags:
        - Authenticatie
      responses:
        "200":
          description: Wachtwoord succesvol gereset

  /api/get-user-info:
    get:
      summary: Gebruikersinformatie ophalen
      description: Haal de informatie op van de ingelogde gebruiker
      security:
        - bearerAuth: []
      tags:
        - Gebruikers
      responses:
        "200":
          description: Gebruikersinformatie succesvol opgehaald
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfo"
        "401":
          description: Niet geautoriseerd

  /api/change-user-info:
    post:
      summary: Gebruikersinformatie wijzigen
      description: Wijzig de informatie van de ingelogde gebruiker
      security:
        - bearerAuth: []
      tags:
        - Gebruikers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInfo"
      responses:
        "200":
          description: Gebruikersinformatie succesvol gewijzigd
        "401":
          description: Niet geautoriseerd

  /api/{hypervisor}/listallvms:
    get:
      summary: Alle virtuele machines ophalen
      description: Haal een lijst op van alle virtuele machines (alleen voor admins)
      security:
        - bearerAuth: []
      tags:
        - Virtuele Machines
      parameters:
        - name: hypervisor
          in: path
          required: true
          schema:
            type: string
          description: Type hypervisor (bijv. proxmox)
      responses:
        "200":
          description: Lijst van alle virtuele machines succesvol opgehaald
        "401":
          description: Niet geautoriseerd
        "403":
          description: Geen admin rechten

  /api/{hypervisor}/listvmsuser:
    get:
      summary: Gebruiker's virtuele machines ophalen
      description: Haal een lijst op van alle virtuele machines van de ingelogde gebruiker
      security:
        - bearerAuth: []
      tags:
        - Virtuele Machines
      parameters:
        - name: hypervisor
          in: path
          required: true
          schema:
            type: string
          description: Type hypervisor (bijv. proxmox)
      responses:
        "200":
          description: Lijst van virtuele machines succesvol opgehaald
        "401":
          description: Niet geautoriseerd

  /api/{hypervisor}/create-server:
    post:
      summary: Nieuwe server aanmaken
      description: Maak een nieuwe virtuele machine aan
      security:
        - bearerAuth: []
      tags:
        - Virtuele Machines
      parameters:
        - name: hypervisor
          in: path
          required: true
          schema:
            type: string
          description: Type hypervisor (bijv. proxmox)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateServerRequest"
      responses:
        "200":
          description: Server succesvol aangemaakt
        "401":
          description: Niet geautoriseerd

  /api/{hypervisor}/delete-server/{vmid}:
    post:
      summary: Server verwijderen
      description: Verwijder een virtuele machine
      security:
        - bearerAuth: []
      tags:
        - Virtuele Machines
      parameters:
        - name: hypervisor
          in: path
          required: true
          schema:
            type: string
          description: Type hypervisor (bijv. proxmox)
        - name: vmid
          in: path
          required: true
          schema:
            type: integer
          description: ID van de virtuele machine
      responses:
        "200":
          description: Server succesvol verwijderd
        "401":
          description: Niet geautoriseerd
        "403":
          description: Geen toegang tot deze VM
